{% set name = "GridDataFormats" %}
{% set version = "1.0.2" %}

package:
  name: griddataformats
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/G/GridDataFormats/GridDataFormats-{{ version }}.tar.gz
  sha256: b93cf7f36fce33dbc428026f26dba560d5c7ba2387caca495bad920f90094502

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy >=1.21
    - scipy
    - mrcfile

test:
  imports:
    - gridData

about:
  home: https://github.com/MDAnalysis/GridDataFormats
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  summary: Reading and writing of data on regular grids in Python
  description: |
    The gridDataFormats package provides classes to unify reading and
    writing n-dimensional datasets. One can read grid data from files,
    make them available as a `Grid` object, and write out the data again.
  doc_url: https://www.mdanalysis.org/GridDataFormats/
  dev_url: https://github.com/MDAnalysis/GridDataFormats

extra:
  recipe-maintainers:
    - IAlibay
    - kain88-de
    - orbeckst
    - richardjgowers
    - IAlibay
