{% set name = "GridDataFormats" %}
{% set version = "0.7.0" %}

package:
  name: griddataformats
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/G/GridDataFormats/GridDataFormats-{{ version }}.tar.gz
  sha256: 021e9505f2f491d0b1ba7045b2912fdb797e5982a942f93f4e4714900b7d29bc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7,<3|>=3.5
    - pip
  run:
    - python >=2.7,<3|>=3.5
    - six
    - numpy >=1.0.3
    - scipy
    - mrcfile

test:
  imports:
    - gridData

about:
  home: https://github.com/MDAnalysis/GridDataFormats
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  summary: Reading and writing of data on regular grids in Python
  description: |
    The gridDataFormats package provides classes to unify reading and
    writing n-dimensional datasets. One can read grid data from files,
    make them available as a `Grid` object, and write out the data again.
  doc_url: https://www.mdanalysis.org/GridDataFormats/
  dev_url: https://github.com/MDAnalysis/GridDataFormats

extra:
  recipe-maintainers:
    - IAlibay
    - kain88-de
    - orbeckst
    - richardjgowers
